# Generated by Django 5.1.7 on 2025-03-19 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='body_en',
            field=models.TextField(default='Empty field', null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='body_ru',
            field=models.TextField(default='Empty field', null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='title_en',
            field=models.CharField(max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='posts',
            name='title_ru',
            field=models.CharField(max_length=75, null=True),
        ),
    ]
