# Generated by Django 5.1.5 on 2025-03-07 08:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('category', '0001_initial'),
        ('subscriber', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_name', models.CharField(default='John Doe', max_length=75)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CategoryMail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='category.category')),
                ('subscriber3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='subscriber.subscriber')),
            ],
            options={
                'unique_together': {('category3', 'subscriber3')},
            },
        ),
    ]
